export const VERTEX_DEFAULTS = Object.freeze({
  LOCATION_ID: "us-central1",
  VEO_MODEL_ID: "veo-3.1-generate-preview",
  ASPECT_RATIO: "9:16",
  RESOLUTION: "720p",
  DURATION_SECONDS: 8,
  SAMPLE_COUNT: 1,
  GENERATE_AUDIO: true,
  PERSON_GENERATION: "allow_all",
  ADD_WATERMARK: true,
  INCLUDE_BAD_REASONS: true,
  MAX_PARALLEL: 1,
  BACKOFF_MS_BASE: 2000,
  BACKOFF_MS_MAX: 20000,
  SOFT_LIMIT_PER_MIN: 20,
  MIN_DELAY_BETWEEN_REQUESTS_MS: 5000
});
